title: Ezra Savard
email: ezra@ezrasavard.com
greeting: Hi, I'm Ezra Savard
description: > # this means to ignore newlines until "baseurl:"
    I'm an engineer who likes coffee, tinkering and weightlifting.
github:  ezrasavard
linkedin: ezrasavard

# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ezrasavard.com" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

# cover images are expected to be 600px by 240px (at least 5:2 aspect ratio)
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Ezra Savard"
            cover: "/media/header.jpg"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Ezra Savard"
            cover: "/media/header.jpg"
            layout: "default"