title: Ezra Savard
email: ezra@ezrasavard.com
greeting: Ezra Savard
description: >
    I'm an engineer who is usually reading, drinking coffee, or lifting weights.
github:  ezrasavard
linkedin: ezrasavard
favicon: favicon.png
# Build settings
paginate: 3
#baseurl: "/demo/" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "http://www.ezrasavard.com" # the base hostname & protocol for your site
highlights: pygments
permalink: posts/:title/
include: ["_pages"]
gems: [jekyll-paginate]
markdown: kramdown
excerpt_separator: "<!--more-->"
sass:
    sass_dir: _sass
    style: compressed

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Ezra Savard"
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            author: "Ezra Savard"
            layout: "page"

